spring:
  data:
    web:
      pageable:
        serialization-mode: via-dto
        one-indexed-parameters: true
        max-page-size: 50

  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never

  application:
    name: campustrack

  datasource:
    url: jdbc:mysql://localhost:3306/campus_track
    username: root
    password: devServer@123n
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    secret: dev_jwt_token_PjmkwUUavaMfAGhlyzL4JO7OKRRLnKJvdIkPUwdOXMi
    issuer: campus-incident-dev-system
    expiration: 86400000

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
